### ISSUE TITLE
Doesn't build on Ubuntu 25.04

### ISSUE THREAD

**Issue by vaskark** [electrickite/batsignal#43]
make:

```
clang -pedantic -Wall -Wextra -Werror -Wno-unused-parameter -Os -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/libmount -I/usr/include/blkid -pthread  -O1   -c -o main.o main.c
In file included from main.c:28:
./notify.h:15:24: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   15 | void close_notification();
      |                        ^
      |                         void
In file included from main.c:29:
./options.h:58:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   58 | char* find_config_file();
      |                       ^
      |                        void
main.c:31:19: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   31 | void print_version()
      |                   ^
      |                    void
main.c:36:16: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   36 | void print_help()
      |                ^
      |                 void
main.c:78:13: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   78 | void cleanup()
      |             ^
      |              void
main.c:85:20: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   85 | void signal_handler()
      |                    ^
      |                     void
6 errors generated.
make: *** [<builtin>: main.o] Error 1
```

Any help would be appreciated.
Thanks.

**Comment by HerbyZ** [comment]
I couldn't compile, but actually solved this problem:
You need to replace all declaration mentioned by compiler, such as
```c
void close_notification();
```
with
```c
void close_notification(void);
```

It fixed the issue, but, as i said, I couldn't compile it anyway. Got this error:
```
clang -pedantic -Wall -Wextra -Werror -Wno-unused-parameter -Os -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glycin-2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -pthread -O1   -c -o main.o main.c
main.c:133:19: error: incompatible function pointer types
      passing 'void (void)' to parameter of type
      '__sighandler_t' (aka 'void (*)(int)')
      [-Wincompatible-function-pointer-types]
  133 |   signal(SIGTERM, signal_handler);
      |                   ^~~~~~~~~~~~~~
/usr/include/signal.h:88:57: note: passing argument to
      parameter '__handler' here
   88 |   ...signal (int __sig, __sighandler_t __handler)
      |                                        ^
main.c:134:18: error: incompatible function pointer types
      passing 'void (void)' to parameter of type
      '__sighandler_t' (aka 'void (*)(int)')
      [-Wincompatible-function-pointer-types]
  134 |   signal(SIGINT, signal_handler);
      |                  ^~~~~~~~~~~~~~
/usr/include/signal.h:88:57: note: passing argument to
      parameter '__handler' here
   88 |   ...signal (int __sig, __sighandler_t __handler)
      |                                        ^
2 errors generated.
make: *** [<builtin>: main.o] Error 1
```
P.S. gcc doesn't produce errors with "old C style" function declaration, so it seems clang specific.

**Comment by dangitsegfault** [comment]
There is a PR (#40) that aims to fix this. It was never merged and got closed but can be used as a reference.
